"""
Database seed script with initial Hindi vocabulary.
Run with: python -m src.db.seed
"""

import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from src.db.database import engine, async_session_maker
from src.db.models import Base, Word, GrammarConcept, User
from src.auth import get_password_hash
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initial Hindi vocabulary - A1 level (beginner)
SEED_WORDS = [
    # Pronouns (सर्वनाम)
    {
        "hindi": "मैं",
        "roman": "main",
        "english": "I",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "तुम",
        "roman": "tum",
        "english": "you (informal)",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "आप",
        "roman": "aap",
        "english": "you (formal)",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "वह",
        "roman": "vah",
        "english": "he/she/that",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "हम",
        "roman": "ham",
        "english": "we",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "वे",
        "roman": "ve",
        "english": "they",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "यह",
        "roman": "yah",
        "english": "this",
        "level": "A1",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "कौन",
        "roman": "kaun",
        "english": "who",
        "level": "A1",
        "pos": "pronoun",
        "category": "question_words",
    },
    {
        "hindi": "क्या",
        "roman": "kya",
        "english": "what",
        "level": "A1",
        "pos": "pronoun",
        "category": "question_words",
    },
    {
        "hindi": "कहाँ",
        "roman": "kahaan",
        "english": "where",
        "level": "A1",
        "pos": "adverb",
        "category": "question_words",
    },
    # Common verbs (क्रिया) - infinitive forms
    {
        "hindi": "होना",
        "roman": "hona",
        "english": "to be",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "करना",
        "roman": "karna",
        "english": "to do",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "जाना",
        "roman": "jaana",
        "english": "to go",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "आना",
        "roman": "aana",
        "english": "to come",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "खाना",
        "roman": "khaana",
        "english": "to eat",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "पीना",
        "roman": "peena",
        "english": "to drink",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "देखना",
        "roman": "dekhna",
        "english": "to see/look",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "सुनना",
        "roman": "sunna",
        "english": "to hear/listen",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "बोलना",
        "roman": "bolna",
        "english": "to speak",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "पढ़ना",
        "roman": "padhna",
        "english": "to read/study",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "लिखना",
        "roman": "likhna",
        "english": "to write",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "सोना",
        "roman": "sona",
        "english": "to sleep",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "उठना",
        "roman": "uthna",
        "english": "to get up",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "चलना",
        "roman": "chalna",
        "english": "to walk",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "रहना",
        "roman": "rehna",
        "english": "to live/stay",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "चाहना",
        "roman": "chaahna",
        "english": "to want",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "समझना",
        "roman": "samajhna",
        "english": "to understand",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "सीखना",
        "roman": "seekhna",
        "english": "to learn",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "देना",
        "roman": "dena",
        "english": "to give",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "लेना",
        "roman": "lena",
        "english": "to take",
        "level": "A1",
        "pos": "verb",
        "category": "verbs",
    },
    # Verb forms (है, हूँ, हैं conjugations)
    {
        "hindi": "हूँ",
        "roman": "hoon",
        "english": "am (I)",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "है",
        "roman": "hai",
        "english": "is",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "हैं",
        "roman": "hain",
        "english": "are",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "हो",
        "roman": "ho",
        "english": "are (you informal)",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "था",
        "roman": "tha",
        "english": "was (masc)",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "थी",
        "roman": "thi",
        "english": "was (fem)",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    {
        "hindi": "थे",
        "roman": "the",
        "english": "were",
        "level": "A1",
        "pos": "verb",
        "category": "verb_forms",
    },
    # Common nouns (संज्ञा)
    {
        "hindi": "घर",
        "roman": "ghar",
        "english": "home/house",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "काम",
        "roman": "kaam",
        "english": "work",
        "level": "A1",
        "pos": "noun",
        "category": "activities",
    },
    {
        "hindi": "पानी",
        "roman": "paani",
        "english": "water",
        "level": "A1",
        "pos": "noun",
        "category": "food_drink",
    },
    {
        "hindi": "चाय",
        "roman": "chai",
        "english": "tea",
        "level": "A1",
        "pos": "noun",
        "category": "food_drink",
    },
    {
        "hindi": "खाना",
        "roman": "khaana",
        "english": "food",
        "level": "A1",
        "pos": "noun",
        "category": "food_drink",
    },
    {
        "hindi": "दिन",
        "roman": "din",
        "english": "day",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    {
        "hindi": "रात",
        "roman": "raat",
        "english": "night",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    {
        "hindi": "समय",
        "roman": "samay",
        "english": "time",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    {
        "hindi": "आदमी",
        "roman": "aadmi",
        "english": "man",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "औरत",
        "roman": "aurat",
        "english": "woman",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "लड़का",
        "roman": "ladka",
        "english": "boy",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "लड़की",
        "roman": "ladki",
        "english": "girl",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "बच्चा",
        "roman": "bachcha",
        "english": "child",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "दोस्त",
        "roman": "dost",
        "english": "friend",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "परिवार",
        "roman": "parivaar",
        "english": "family",
        "level": "A1",
        "pos": "noun",
        "category": "people",
    },
    {
        "hindi": "माँ",
        "roman": "maa",
        "english": "mother",
        "level": "A1",
        "pos": "noun",
        "category": "family",
    },
    {
        "hindi": "पिता",
        "roman": "pita",
        "english": "father",
        "level": "A1",
        "pos": "noun",
        "category": "family",
    },
    {
        "hindi": "भाई",
        "roman": "bhai",
        "english": "brother",
        "level": "A1",
        "pos": "noun",
        "category": "family",
    },
    {
        "hindi": "बहन",
        "roman": "behen",
        "english": "sister",
        "level": "A1",
        "pos": "noun",
        "category": "family",
    },
    {
        "hindi": "नाम",
        "roman": "naam",
        "english": "name",
        "level": "A1",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "बात",
        "roman": "baat",
        "english": "thing/matter/talk",
        "level": "A1",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "जगह",
        "roman": "jagah",
        "english": "place",
        "level": "A1",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "देश",
        "roman": "desh",
        "english": "country",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "शहर",
        "roman": "sheher",
        "english": "city",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "गाँव",
        "roman": "gaanv",
        "english": "village",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "दुकान",
        "roman": "dukaan",
        "english": "shop",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "स्कूल",
        "roman": "school",
        "english": "school",
        "level": "A1",
        "pos": "noun",
        "category": "places",
    },
    {
        "hindi": "किताब",
        "roman": "kitaab",
        "english": "book",
        "level": "A1",
        "pos": "noun",
        "category": "objects",
    },
    {
        "hindi": "फ़ोन",
        "roman": "phone",
        "english": "phone",
        "level": "A1",
        "pos": "noun",
        "category": "objects",
    },
    # Adjectives (विशेषण)
    {
        "hindi": "अच्छा",
        "roman": "achcha",
        "english": "good",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "बुरा",
        "roman": "bura",
        "english": "bad",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "बड़ा",
        "roman": "bada",
        "english": "big",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "छोटा",
        "roman": "chhota",
        "english": "small",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "नया",
        "roman": "naya",
        "english": "new",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "पुराना",
        "roman": "puraana",
        "english": "old (thing)",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "सुंदर",
        "roman": "sundar",
        "english": "beautiful",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "खुश",
        "roman": "khush",
        "english": "happy",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "गर्म",
        "roman": "garam",
        "english": "hot",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "ठंडा",
        "roman": "thanda",
        "english": "cold",
        "level": "A1",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "सफ़ेद",
        "roman": "safed",
        "english": "white",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    {
        "hindi": "काला",
        "roman": "kaala",
        "english": "black",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    {
        "hindi": "लाल",
        "roman": "laal",
        "english": "red",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    {
        "hindi": "हरा",
        "roman": "hara",
        "english": "green",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    {
        "hindi": "नीला",
        "roman": "neela",
        "english": "blue",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    {
        "hindi": "पीला",
        "roman": "peela",
        "english": "yellow",
        "level": "A1",
        "pos": "adjective",
        "category": "colors",
    },
    # Numbers (संख्या)
    {
        "hindi": "एक",
        "roman": "ek",
        "english": "one",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "दो",
        "roman": "do",
        "english": "two",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "तीन",
        "roman": "teen",
        "english": "three",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "चार",
        "roman": "chaar",
        "english": "four",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "पाँच",
        "roman": "paanch",
        "english": "five",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "छह",
        "roman": "chhah",
        "english": "six",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "सात",
        "roman": "saat",
        "english": "seven",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "आठ",
        "roman": "aath",
        "english": "eight",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "नौ",
        "roman": "nau",
        "english": "nine",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    {
        "hindi": "दस",
        "roman": "das",
        "english": "ten",
        "level": "A1",
        "pos": "number",
        "category": "numbers",
    },
    # Time expressions
    {
        "hindi": "आज",
        "roman": "aaj",
        "english": "today",
        "level": "A1",
        "pos": "adverb",
        "category": "time",
    },
    {
        "hindi": "कल",
        "roman": "kal",
        "english": "yesterday/tomorrow",
        "level": "A1",
        "pos": "adverb",
        "category": "time",
    },
    {
        "hindi": "अभी",
        "roman": "abhi",
        "english": "now",
        "level": "A1",
        "pos": "adverb",
        "category": "time",
    },
    {
        "hindi": "बाद में",
        "roman": "baad mein",
        "english": "later",
        "level": "A1",
        "pos": "adverb",
        "category": "time",
    },
    {
        "hindi": "पहले",
        "roman": "pehle",
        "english": "before/earlier",
        "level": "A1",
        "pos": "adverb",
        "category": "time",
    },
    {
        "hindi": "सुबह",
        "roman": "subah",
        "english": "morning",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    {
        "hindi": "शाम",
        "roman": "shaam",
        "english": "evening",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    {
        "hindi": "दोपहर",
        "roman": "dopahar",
        "english": "afternoon",
        "level": "A1",
        "pos": "noun",
        "category": "time",
    },
    # Common adverbs and particles
    {
        "hindi": "बहुत",
        "roman": "bahut",
        "english": "very/much",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "थोड़ा",
        "roman": "thoda",
        "english": "a little",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "यहाँ",
        "roman": "yahaan",
        "english": "here",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "वहाँ",
        "roman": "vahaan",
        "english": "there",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "फिर",
        "roman": "phir",
        "english": "then/again",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "भी",
        "roman": "bhi",
        "english": "also/too",
        "level": "A1",
        "pos": "particle",
        "category": "particles",
    },
    {
        "hindi": "ही",
        "roman": "hi",
        "english": "only/emphatic",
        "level": "A1",
        "pos": "particle",
        "category": "particles",
    },
    {
        "hindi": "नहीं",
        "roman": "nahin",
        "english": "no/not",
        "level": "A1",
        "pos": "adverb",
        "category": "adverbs",
    },
    {
        "hindi": "हाँ",
        "roman": "haan",
        "english": "yes",
        "level": "A1",
        "pos": "interjection",
        "category": "general",
    },
    # Postpositions (परसर्ग)
    {
        "hindi": "में",
        "roman": "mein",
        "english": "in",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "पर",
        "roman": "par",
        "english": "on/at",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "को",
        "roman": "ko",
        "english": "to (dative)",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "से",
        "roman": "se",
        "english": "from/with/by",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "का",
        "roman": "ka",
        "english": "of (masc)",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "की",
        "roman": "ki",
        "english": "of (fem)",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "के",
        "roman": "ke",
        "english": "of (plural)",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "के लिए",
        "roman": "ke liye",
        "english": "for",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "के साथ",
        "roman": "ke saath",
        "english": "with",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "के बाद",
        "roman": "ke baad",
        "english": "after",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    {
        "hindi": "के पास",
        "roman": "ke paas",
        "english": "near/have",
        "level": "A1",
        "pos": "postposition",
        "category": "postpositions",
    },
    # Common phrases
    {
        "hindi": "नमस्ते",
        "roman": "namaste",
        "english": "hello",
        "level": "A1",
        "pos": "interjection",
        "category": "greetings",
    },
    {
        "hindi": "धन्यवाद",
        "roman": "dhanyavaad",
        "english": "thank you",
        "level": "A1",
        "pos": "interjection",
        "category": "greetings",
    },
    {
        "hindi": "माफ़ कीजिए",
        "roman": "maaf keejiye",
        "english": "excuse me/sorry",
        "level": "A1",
        "pos": "phrase",
        "category": "greetings",
    },
    {
        "hindi": "ठीक",
        "roman": "theek",
        "english": "okay/fine",
        "level": "A1",
        "pos": "adjective",
        "category": "general",
    },
    {
        "hindi": "और",
        "roman": "aur",
        "english": "and/more",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    {
        "hindi": "या",
        "roman": "ya",
        "english": "or",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    {
        "hindi": "लेकिन",
        "roman": "lekin",
        "english": "but",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    {
        "hindi": "क्योंकि",
        "roman": "kyonki",
        "english": "because",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    {
        "hindi": "अगर",
        "roman": "agar",
        "english": "if",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    {
        "hindi": "तो",
        "roman": "to",
        "english": "then/so",
        "level": "A1",
        "pos": "conjunction",
        "category": "conjunctions",
    },
    # A2 Level additions
    {
        "hindi": "मिलना",
        "roman": "milna",
        "english": "to meet/to get",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "बताना",
        "roman": "batana",
        "english": "to tell",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "पूछना",
        "roman": "poochhna",
        "english": "to ask",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "सोचना",
        "roman": "sochna",
        "english": "to think",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "मानना",
        "roman": "maanna",
        "english": "to believe/accept",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "लगना",
        "roman": "lagna",
        "english": "to seem/feel",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "बनाना",
        "roman": "banana",
        "english": "to make",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "खोलना",
        "roman": "kholna",
        "english": "to open",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "बंद करना",
        "roman": "band karna",
        "english": "to close",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "भेजना",
        "roman": "bhejna",
        "english": "to send",
        "level": "A2",
        "pos": "verb",
        "category": "verbs",
    },
    {
        "hindi": "मदद",
        "roman": "madad",
        "english": "help",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "ज़रूरत",
        "roman": "zaroorat",
        "english": "need",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "सवाल",
        "roman": "sawaal",
        "english": "question",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "जवाब",
        "roman": "jawaab",
        "english": "answer",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "कहानी",
        "roman": "kahani",
        "english": "story",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "ज़िंदगी",
        "roman": "zindagi",
        "english": "life",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "दुनिया",
        "roman": "duniya",
        "english": "world",
        "level": "A2",
        "pos": "noun",
        "category": "general",
    },
    {
        "hindi": "हर",
        "roman": "har",
        "english": "every/each",
        "level": "A2",
        "pos": "adjective",
        "category": "adjectives",
    },
    {
        "hindi": "कुछ",
        "roman": "kuch",
        "english": "some/something",
        "level": "A2",
        "pos": "pronoun",
        "category": "pronouns",
    },
    {
        "hindi": "सब",
        "roman": "sab",
        "english": "all/everyone",
        "level": "A2",
        "pos": "pronoun",
        "category": "pronouns",
    },
]

# Grammar concepts
SEED_GRAMMAR = [
    {
        "name": "Subject-Object-Verb Word Order",
        "level": "A1",
        "explanation": "Hindi follows SOV order: Subject comes first, then Object, then Verb. Example: मैं खाना खाता हूँ (I food eat-am) = 'I eat food'",
        "examples": ["मैं पानी पीता हूँ", "वह किताब पढ़ती है", "हम घर जाते हैं"],
    },
    {
        "name": "Gender in Hindi Nouns",
        "level": "A1",
        "explanation": "All Hindi nouns are either masculine or feminine. Words ending in आ (-aa) are usually masculine, words ending in ई (-i) are usually feminine. Gender affects verb conjugation and adjective agreement.",
        "examples": [
            "लड़का (boy) - masculine",
            "लड़की (girl) - feminine",
            "पानी (water) - masculine",
        ],
    },
    {
        "name": "Present Tense होना (to be)",
        "level": "A1",
        "explanation": "The verb होना conjugates as: मैं हूँ, तुम हो, वह/यह है, हम/आप/वे हैं. It's used both as a standalone verb and as an auxiliary.",
        "examples": ["मैं खुश हूँ", "वह अच्छा है", "हम यहाँ हैं"],
    },
    {
        "name": "Postpositions",
        "level": "A1",
        "explanation": "Unlike English prepositions, Hindi uses postpositions that come AFTER the noun. Common ones: में (in), पर (on), को (to), से (from), का/की/के (of).",
        "examples": [
            "घर में (in the house)",
            "मेज़ पर (on the table)",
            "दिल्ली से (from Delhi)",
        ],
    },
    {
        "name": "Oblique Case",
        "level": "A1",
        "explanation": "Nouns change form before postpositions. Masculine -aa ending changes to -e: लड़का → लड़के को. Feminine nouns don't change in singular.",
        "examples": ["लड़का → लड़के को", "घर → घर में", "लड़की → लड़की को"],
    },
    {
        "name": "Present Habitual Tense",
        "level": "A1",
        "explanation": "For regular actions, use verb stem + ता/ती/ते + हूँ/है/हो/हैं. The ending agrees with subject's gender and number.",
        "examples": ["मैं रोज़ पढ़ता हूँ (I read daily)", "वह चाय पीती है (She drinks tea)"],
    },
    {
        "name": "Negation with नहीं",
        "level": "A1",
        "explanation": "Place नहीं before the verb to negate. मैं जाता हूँ → मैं नहीं जाता हूँ. In colloquial speech, the auxiliary is often dropped.",
        "examples": ["मैं नहीं जाता (I don't go)", "वह नहीं आई (She didn't come)"],
    },
    {
        "name": "Question Formation",
        "level": "A2",
        "explanation": "Yes/no questions: add क्या at the beginning OR use rising intonation. Wh-questions: use क्या (what), कौन (who), कहाँ (where), कब (when), क्यों (why), कैसे (how).",
        "examples": ["क्या आप हिंदी बोलते हैं?", "आप कहाँ जाते हैं?", "यह क्या है?"],
    },
    {
        "name": "Past Tense (Simple Past)",
        "level": "A2",
        "explanation": "Use verb stem + आ/ई/ए/ईं. Gender/number agreement with subject (intransitive) or object (transitive). Add था/थी/थे for emphasis.",
        "examples": [
            "वह गया (He went)",
            "वह गई (She went)",
            "मैंने खाना खाया (I ate food)",
        ],
    },
    {
        "name": "Ergative Case with ने",
        "level": "A2",
        "explanation": "In past tense with transitive verbs, the subject takes ने and the verb agrees with the object, not the subject.",
        "examples": ["मैंने किताब पढ़ी", "उसने खाना खाया", "हमने फिल्म देखी"],
    },
]


async def seed_database():
    """Seed the database with initial vocabulary and grammar concepts."""
    async with engine.begin() as conn:
        # Create all tables
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_maker() as session:
        # Check if already seeded
        from sqlalchemy import select, func

        word_count = await session.scalar(select(func.count(Word.id)))

        if word_count and word_count > 0:
            logger.info(f"Database already has {word_count} words. Skipping seed.")
            return

        # Map POS string to enum
        pos_map = {
            "pronoun": "PRONOUN",
            "verb": "VERB",
            "noun": "NOUN",
            "adjective": "ADJECTIVE",
            "adverb": "ADVERB",
            "postposition": "POSTPOSITION",
            "particle": "PARTICLE",
            "conjunction": "CONJUNCTION",
            "interjection": "NOUN",  # Map to noun as fallback
            "number": "NOUN",  # Map to noun as fallback
            "phrase": "NOUN",  # Map to noun as fallback
        }
        
        from src.db.models import PartOfSpeech, CEFRLevel

        # Add words
        logger.info(f"Seeding {len(SEED_WORDS)} words...")
        for word_data in SEED_WORDS:
            word = Word(
                hindi=word_data["hindi"],
                romanized=word_data["roman"],
                english=word_data["english"],
                cefr_level=CEFRLevel(word_data["level"]),
                part_of_speech=PartOfSpeech(pos_map.get(word_data["pos"], "NOUN")),
                tags=[word_data.get("category", "general")],
            )
            session.add(word)

        # Add grammar concepts
        logger.info(f"Seeding {len(SEED_GRAMMAR)} grammar concepts...")
        for i, grammar_data in enumerate(SEED_GRAMMAR):
            # Create slug from name
            slug = grammar_data["name"].lower().replace(" ", "-").replace("(", "").replace(")", "")
            slug = "".join(c for c in slug if c.isalnum() or c == "-")
            grammar = GrammarConcept(
                name=grammar_data["name"],
                slug=slug,
                cefr_level=CEFRLevel(grammar_data["level"]),
                description=grammar_data["explanation"],
                examples_json=grammar_data["examples"],
                sort_order=i,
            )
            session.add(grammar)

        # Create a demo user
        demo_user = User(
            email="demo@example.com",
            hashed_password=get_password_hash("demo123"),
            name="Demo User",
        )
        session.add(demo_user)

        await session.commit()
        logger.info("Database seeded successfully!")


if __name__ == "__main__":
    asyncio.run(seed_database())
